//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARRIENDO_SERVICIO_EXTRA
    {
        public decimal ID { get; set; }
        public decimal ID_SERVICIO_EXTRA { get; set; }
        public decimal ID_ARRIENDO { get; set; }
    
        public virtual ARRIENDO ARRIENDO { get; set; }
        public virtual SERVICIOS_EXTRA SERVICIOS_EXTRA { get; set; }
    }
}
