//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARRIENDO_PERSONA
    {
        public decimal ID { get; set; }
        public decimal ID_ARRIENDO { get; set; }
        public decimal ID_PERSONA { get; set; }
    
        public virtual ARRIENDO ARRIENDO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
