//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABITACIONE
    {
        public decimal ID { get; set; }
        public decimal METROS_CUADRADOS { get; set; }
        public decimal ID_TIPO_HABITACION { get; set; }
        public decimal ID_DEPARTAMENTO { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual TIPO_HABITACION TIPO_HABITACION { get; set; }
    }
}
