//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENTE
    {
        public decimal ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal ID_DEPTO_INVENTARIO { get; set; }
        public string COMENTARIO { get; set; }
    
        public virtual DEPARTAMENTO_INVENTARIO DEPARTAMENTO_INVENTARIO { get; set; }
    }
}
