//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_PERSONA
    {
        public decimal ID { get; set; }
        public decimal ID_PERSONA { get; set; }
        public string STATEMENT { get; set; }
        public decimal ID_EMPLEADO { get; set; }
        public System.DateTime DATE { get; set; }
        public System.DateTime TIME { get; set; }
        public string TABLE { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
