//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR()
        {
            this.TOUR_PERSONA = new HashSet<TOUR_PERSONA>();
        }
    
        public decimal ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime HORA { get; set; }
        public decimal ID_TOUR_LUGAR { get; set; }
        public decimal ID_CHOFER { get; set; }
        public decimal ID_VEHICULO { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual TOUR_LUGAR TOUR_LUGAR { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOUR_PERSONA> TOUR_PERSONA { get; set; }
    }
}
