//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTE
    {
        public decimal ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime HORA { get; set; }
        public string PUNTO_INICIO { get; set; }
        public string PUNTO_FINAL { get; set; }
        public decimal ID_PERSONA { get; set; }
        public decimal ID_VEHICULO { get; set; }
        public decimal NUMERO_PERSONAS { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
    }
}
