//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrealEntities : DbContext
    {
        public TrealEntities()
            : base("name=TrealEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARRIENDO> ARRIENDOes { get; set; }
        public virtual DbSet<ARRIENDO_PERSONA> ARRIENDO_PERSONA { get; set; }
        public virtual DbSet<ARRIENDO_SERVICIO_EXTRA> ARRIENDO_SERVICIO_EXTRA { get; set; }
        public virtual DbSet<COMUNA> COMUNAs { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTOes { get; set; }
        public virtual DbSet<DEPARTAMENTO_FOTOS> DEPARTAMENTO_FOTOS { get; set; }
        public virtual DbSet<DEPARTAMENTO_INVENTARIO> DEPARTAMENTO_INVENTARIO { get; set; }
        public virtual DbSet<ESTADO> ESTADOS { get; set; }
        public virtual DbSet<HABITACIONE> HABITACIONES { get; set; }
        public virtual DbSet<INCIDENTE> INCIDENTES { get; set; }
        public virtual DbSet<INVENTARIO> INVENTARIOs { get; set; }
        public virtual DbSet<LOG_PERSONA> LOG_PERSONA { get; set; }
        public virtual DbSet<MANTENCION> MANTENCIONs { get; set; }
        public virtual DbSet<PAGO> PAGOes { get; set; }
        public virtual DbSet<PERSONA> PERSONAs { get; set; }
        public virtual DbSet<PERSONA_FOTO> PERSONA_FOTO { get; set; }
        public virtual DbSet<PROVINCIA> PROVINCIAs { get; set; }
        public virtual DbSet<REGION> REGIONs { get; set; }
        public virtual DbSet<RESERVA> RESERVAs { get; set; }
        public virtual DbSet<ROL> ROLs { get; set; }
        public virtual DbSet<SERVICIOS_EXTRA> SERVICIOS_EXTRA { get; set; }
        public virtual DbSet<TIPO_HABITACION> TIPO_HABITACION { get; set; }
        public virtual DbSet<TIPO_PAGO> TIPO_PAGO { get; set; }
        public virtual DbSet<TOUR> TOURs { get; set; }
        public virtual DbSet<TOUR_LUGAR> TOUR_LUGAR { get; set; }
        public virtual DbSet<TOUR_PERSONA> TOUR_PERSONA { get; set; }
        public virtual DbSet<TRANSPORTE> TRANSPORTEs { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<VEHICULO> VEHICULOes { get; set; }
        public virtual DbSet<VEHICULO_MARCA> VEHICULO_MARCA { get; set; }
        public virtual DbSet<VEHICULO_MODELO> VEHICULO_MODELO { get; set; }
        public virtual DbSet<VEHICULO_TIPO> VEHICULO_TIPO { get; set; }
    }
}
