//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICULO()
        {
            this.TOURs = new HashSet<TOUR>();
            this.TRANSPORTEs = new HashSet<TRANSPORTE>();
        }
    
        public decimal ID { get; set; }
        public string PATENTE { get; set; }
        public string COLOR { get; set; }
        public string IMAGEN { get; set; }
        public decimal ID_VEHICULO_TIPO { get; set; }
        public decimal ID_VEHICULO_MARCA { get; set; }
        public decimal ID_VEHICULO_MODELO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOUR> TOURs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSPORTE> TRANSPORTEs { get; set; }
        public virtual VEHICULO_MARCA VEHICULO_MARCA { get; set; }
        public virtual VEHICULO_MODELO VEHICULO_MODELO { get; set; }
        public virtual VEHICULO_TIPO VEHICULO_TIPO { get; set; }
    }
}
